### ISSUE TITLE
FB is not defined

### ISSUE THREAD

**Issue by zeeshanjan82** [zyramedia/ng2-facebook-sdk#1]
After installing this library and putting the init code in constructor I get the error: FB is not defined. The issue is coming in this line in the library: 
```js
    FacebookService.prototype.init = function (params) {
        FB.init(params);
    };
```

**Comment by ihadeed** [comment]
Hey there,

Can you share the code you are using?

Also, see here: https://github.com/zyramedia/ng2-facebook-sdk#initparams-facebookinitparams-void

**Comment by zeeshanjan82** [comment]
I was able to fix this issue by adding reference to facebook sdk url but it is not mentioned in readme probable readme needs an update. But now I m getting error in google chrome which is related to script being blocked by the browser but it works fine on ie
