### ISSUE TITLE
FB is not define 

### ISSUE THREAD

**Issue by ashjha** [zyramedia/ng2-facebook-sdk#19]
error_handler.js:47EXCEPTION: Uncaught (in promise): Error: Error in ./LoginComponent class LoginComponent_Host - inline template:0:0 caused by: FB is not defined

**Comment by ihadeed** [comment]
@ashjha did you load the Facebook JavaScript SDK in your index.html ?

**Comment by ashjha** [comment]
Ooops ! sorry now it is working thank you :)

**Comment by ihadeed** [comment]
You're welcome :) @ashjha

**Comment by ashjha** [comment]
Hey ! sometimes angular 2 load before loading sdk any solution for that ?

**Comment by ihadeed** [comment]
@ashjha are you using `async` tag when including their `.js` file? If you are using it, take that out so it loads as soon as the user goes on the page. 

If that still doesn't solve your issue, you can add a timeout on the method that is running on startup.

**Comment by ashjha** [comment]
No , here is my code 

<script>
  (function(d, s, id) {
    var js, fjs = d.getElementsByTagName(s)[0];
    if (d.getElementById(id)) return;
    js = d.createElement(s); js.id = id;
    js.src = "//connect.facebook.net/en_US/sdk.js";
    fjs.parentNode.insertBefore(js, fjs);
  }(document, 'script', 'facebook-jssdk'));
</script>

<app-root>
  <div class="loader"></div>
</app-root>

**Comment by ihadeed** [comment]
Yeah instead of that, use this:
```
<script type="text/javascript" src="https://connect.facebook.net/en_US/sdk.js"></script>
```

**Comment by ashjha** [comment]
Solved , Thank you again :+1: )

**Comment by ihadeed** [comment]
You're welcome @ashjha !

**Comment by kiranpwt** [comment]
video share in facebook ... error occurs ReferenceError: FB is not defined 
my code is see
function init_fb(){
             window.fbAsyncInit = function() {
                 app_id = document.getElementById('fb_app_id').value;
		    FB.init({
                      appId            : app_id,
                      autoLogAppEvents : true,
                      xfbml            : true,
                      version          : 'v2.12'
                    });
                  };

                  (function(d, s, id){
                     var js, fjs = d.getElementsByTagName(s)[0];
                     if (d.getElementById(id)) {return;}
                     js = d.createElement(s); js.id = id;
                     js.src = "https://connect.facebook.net/en_US/sdk.js";
                     fjs.parentNode.insertBefore(js, fjs);
                   }(document, 'script', 'facebook-jssdk'));
		
	}
        
	function call_fb_share(){
			site_name = "Musical Names";
			site_url = "http://musicalnames.com";
			fb_shar_image = "http://musicalnames.com/ecards/images/user_images/thumbs/thumb-fb_10942740_1581202525431718_323317920938951800_n.jpg.jpg";
			detail_description = '<b>This is testing for desc <b>' ;
	
                FB.ui({
			method: 'feed',
			name: site_name,
			link: site_url,
			picture: fb_shar_image,
			caption: 'Musical Names E-card',
			description: detail_description,
			message: 'fb message'
		}, function(response){});
               
	
	}
    plz any solution...
