### ISSUE TITLE
Ionic 2 - FB is not defined

### ISSUE THREAD

**Issue by jlsuarezs** [zyramedia/ng2-facebook-sdk#2]
HI,

I am trying to use your module in Ionic 2 without success.

Error:
     FB is not defined

And I've already executed:

```
let fbParams: FacebookInitParams = {
                                   appId: '111111',
                                   status     : true,
                                   xfbml      : true,
                                   version: 'v2.6'
                                   };
this.fb.init(fbParams);
```
Any help?

Thank you!

**Comment by ihadeed** [comment]
Hey there,

Did you include the Facebook JavaScript SDK in your index.html ?

**Comment by ihadeed** [comment]
If you are developing a native mobile app with Ionic 2 I suggest that you have a look at this http://ionicframework.com/docs/v2/native/facebook/

That plugin uses the native Android/iOS Facebook SDKs. It performs better on mobile devices. It also uses the existing session if you are logged in via the Facebook app, unlike the JavaScript SDK which opens up the browser and asks you to login.

I've only tested this repo on web apps that use Angular 2, I'm not so sure how it is on Ionic apps.

**Comment by Traveller198** [comment]
Hi ihadeed,

                  I am using system.config.js....it throws error Error: (SystemJS) XHR error (404 Not Found) loading http://localhost:3000/ng2-facebook-sdk Error: XHR error (404 Not Found) loading http://localhost:3000/ng2-facebook-sdk at XMLHttpRequest.
Can you plsease help me.Thanks

**Comment by ihadeed** [comment]
Wrong place to ask a question @Traveller198 .. Have a look here https://github.com/zyra/ngx-facebook/issues/76#issuecomment-299762196 if you're using `ngx-facebook` or here https://github.com/zyra/ngx-facebook/issues/25 for `ng2-facebook-sdk`.
