### ISSUE TITLE
FacebookUiParams interface is missing a required attribute

### ISSUE THREAD

**Issue by AArmin** [zyramedia/ng2-facebook-sdk#22]
I've tried using the ui method for a share dialog, but it's interface is missing a required href attribute so I cannot pass FacebookUiParams correctly. I've created a pull request that takes care of this.

**Comment by photostu** [comment]
Any chance of getting this PR merged?
+1 on this issue

**Comment by ihadeed** [comment]
Just pushed a commit that completes the UI typings :) please update to latest version.
