### ISSUE TITLE
FB is not defined

### ISSUE THREAD

**Issue by snstarosciak** [zyramedia/ng2-facebook-sdk#23]
Hey there,

I've added this npm module to my project and followed all of the instructions, however when I try to load my app it says "FB is not defined". Any idea what this could be?

**Comment by ihadeed** [comment]
Did you include the Facebook JavaScript SDK in your index.html file?

**Comment by snstarosciak** [comment]
Hey man, thanks for replying so quickly. Yes I did. Here's the code I'm using that's causing the problem.

In my users.provider.ts file:

```
import { Injectable } from '@angular/core';
import { Events } from 'ionic-angular';
import { Storage } from '@ionic/storage';
import {FacebookService, FacebookInitParams} from 'ng2-facebook-sdk/dist';

@Injectable()
export class Users {

  constructor(
    public events: Events,
    public storage: Storage,
    private fb: FacebookService
  ) {
    let fbParams: FacebookInitParams = {
                                   appId: '*************',
                                   xfbml: true,
                                   version: 'v2.6'
                                   };
    this.fb.init(fbParams);
  }
}
```

Inside of my app.module.ts:

```
import { FacebookService } from 'ng2-facebook-sdk/dist';

...

@NgModule({
  declarations: [],
  imports: [],
  providers: [FacebookService]
});
```

I should note that I'm also using Ionic 2 . Here is a snippet from my package.json

```
{
  "dependencies": {
    "@angular/common": "2.0.0",
    "@angular/compiler": "2.0.0",
    "@angular/compiler-cli": "0.6.2",
    "@angular/core": "2.0.0",
    "@angular/forms": "2.0.0",
    "@angular/http": "2.0.0",
    "@angular/platform-browser": "2.0.0",
    "@angular/platform-browser-dynamic": "2.0.0",
    "@angular/platform-server": "2.0.0",
    "@ionic/storage": "1.0.3",
    "angularfire2": "^2.0.0-beta.5",
    "firebase": "^3.5.2",
    "ionic-angular": "2.0.0-rc.1",
    "ionic-native": "2.2.3",
    "ionicons": "3.0.0",
    "moment": "2.15.1",
    "ng-semantic": "^1.1.11",
    "rxjs": "5.0.0-beta.12",
    "zone.js": "0.6.21"
  },
  "devDependencies": {
    "@ionic/app-scripts": "^0.0.36",
    "@types/request": "0.0.30",
    "ng2-facebook-sdk": "^0.4.0",
    "typescript": "^2.0.3"
  },
  "cordovaPlugins": [
    "cordova-plugin-whitelist",
    {
      "locator": "https://github.com/VersoSolutions/CordovaClipboard",
      "id": "com.verso.cordova.clipboard"
    },
    {
      "locator": "https://github.com/apache/cordova-plugin-splashscreen.git",
      "id": "cordova-plugin-splashscreen"
    },
    "cordova-plugin-crosswalk-webview"
  ],
  "cordovaPlatforms": [
    "ios",
    "android"
  ]
}
```

I should also note that in order to get this npm module to be picked up by webpack and exported, I had to add it into the Ionic rollup config in "/node_modules/@ionic/app-scripts/config/rollup.config.js"

So with all that being said, what do you think I'm missing here?

**Comment by SimoneCafiero** [comment]
Hi,
on my side I got this message:

> 404 GET <PATH>/node_modules/ng2-facebook-sdk/dist.js

I included in index.html what follows:

> <script type="text/javascript" src="https://connect.facebook.net/en_US/sdk.js"></script>

Then in the systemjs.config.js:

```
map: {
  ...
 'ng2-facebook-sdk': 'npm:ng2-facebook-sdk'
},
packages: {
  ...
'ng2-facebook-sdk': {
                main: './ng2-facebook-sdk.js',
                defaultExtension: 'js'
            }

``````

Any idea?

**Comment by ihadeed** [comment]
I don't see a problem with your code. Can you double check that this line `<script src="https://connect.facebook.net/en_US/sdk.js"></script>` is in your `index.html` before importing the app's main JavaScript file?

**Comment by bencameron00** [comment]
Was there any solution to this problem? I am having the same issue.

**Comment by ihadeed** [comment]
@bencameron00 see my last comment. Are you including the Facebook SDK JavaScript file before your app's code?

**Comment by bencameron00** [comment]
I sure do. The last line of the 'head' section is...

<script type="text/javascript" src="https://connect.facebook.net/en_US/sdk.js"></script>

My main app is declared after that.

In one of my components I am trying to call the below which is causing the error...

        let fbParams: FacebookInitParams = {
            appId: 'XXX',
            xfbml: true,
            version: 'v2.6'
        };
        this.fb.init(fbParams);

**Comment by ihadeed** [comment]
@bencameron00 what is the exact error you're getting? do you have any Ad blockers, Tracker blockers, Widget blockers installed on your browser (they sometimes block the facebook script)?

**Comment by bencameron00** [comment]
No blockers at all. I am seeing this error...

An unhandled exception occurred while processing the request.

Exception: Call to Node module failed with error: Error: Uncaught (in promise): ReferenceError: FB is not defined
ReferenceError: FB is not defined
at FacebookService.init (C:\Projects\TileCase.V2\TileCase.V2.JavaScriptServices\ClientApp\dist\main-server.js:21474:9)

**Comment by AlanMc74** [comment]
HI, I know you closed this, but I was wondering did you ever come up with a fix for it? I am having the exact same issue, I can create a small barebones project tomorrow and send it on tomorrow if you haven't found a fix yet but still want to check out what might be the problem.

**Comment by ihadeed** [comment]
@AlanMc74 

what are the issues you're experiencing exactly? please open a new issue with details.

**Comment by muzammilsudofy** [comment]
Facing the same issue ? Does anyone have the solution ?

**Comment by bencameron00** [comment]
Do you have the script tag on your page?
<script type="text/javascript" src="https://connect.facebook.net/en_US/sdk.js"></script>

Adding that fixed it for me.

**Comment by abel672** [comment]
Hi guys, here you have my solution. I had the same problem and I couln't fix it even adding the script in the index.html. SOLUTION:
What I did is to uninstall the ngx-facebook package from my project 'npm uninstall ngx-facebook'
and install it again but with the 'npm install ngx-facebook' command instead the 'npm i --save ngx-facebook' that the docst offers you. That fix the problem for me. Hope that will fix yours.

**Comment by utiq** [comment]
So, the way to fix this is to add
**<script type="text/javascript" src="https://connect.facebook.net/en_US/sdk.js"></script>**
but at the end of the html file, check this example

```
<!doctype html>
<html>
<head>
  <meta charset="utf-8">
  <title>Title</title>
  <base href="/">

  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="icon" type="image/x-icon" href="favicon.ico">
</head>
<body>
  <app-root>Loading...</app-root>
</body>
<script type="text/javascript" src="https://connect.facebook.net/en_US/sdk.js"></script>
</html>
```
