### ISSUE TITLE
FB Login email permissions

### ISSUE THREAD

**Issue by Arf291** [zyramedia/ng2-facebook-sdk#24]
Hello, 

I have used this library and it works perfectly, but I would like to know how to get the logged user's email. I Facebook Developers documentation it says we can ask for [different permissions](https://developers.facebook.com/docs/facebook-login/permissions) besides the default basic ones. Well, I have read that it can be asked in the Login() method, as it can be seen in the [Javascript SDK Login documentation](https://developers.facebook.com/docs/reference/javascript/FB.login/v2.8#permissions). But I don't know how to it with this Typescript version. 

Thank you in advance.

Regards,

Alberto.

**Comment by Arf291** [comment]
I got it. In case it is useful, I just created a `FacebookLoginOptions` variable with `scope` attribute with `email` value, when calling the login function. Then in the API call for getting user data I added the email in the fields list  In the reference documentation I left before it is explained, but not for Typescript. 

This is the example code: 
```
       let loginOption: FacebookLoginOptions = {
            scope: 'email'
        };

        this.facebookService.login(loginOptions).then(
            (response: FacebookLoginResponse) => {
                // ...
                this.getFacebookData();
            },
            (error: any) => console.error(error)
        );
        
       // Facebook API call for getting user data
       public getFacebookData() {
            this.facebookService.api('/me?fields=id,name,first_name,gender,email').then(
                (response: any) => {
                    console.log('Email: ', response.email);
                },
                (error: any) => console.error(error)
            );
        }
```

**Comment by danielptm** [comment]
I cannot get the email address. And I am using code very similar to the above. I can get other values, but for some reason email is not apart of the returned json object


```
  options: LoginOptions = {
    scope: 'email,public_profile'
  };
```
...
  ```
facebooklogin(){

    this.fb.login(this.options)
      .then((response: LoginResponse) => {
        this.showData(response)
      })
      .catch(e => console.error('Error logging in'));

  }

    showData(data){
      console.log(data);
      this.fb.api('/me?fields=email,name')
        .then((res:any)=>console.log(res))
        .catch(e=> console.log(e));


    }
```

returns
{name: "<my name>", id: "<my id>"}

but not email

**Comment by danielptm** [comment]
super wierd...For some reason it has something to do with my developer account I think. I have a primary email address registered with the Facebook profile that I am using, but for some reason the email is not retrieved. I decided to create another Facebook account, I then added this account to the developer account, and i can get the email address from that account....Anyway if somebody has this problem,  and you're doing the above steps, try getting the email from a different Facebook account, which might involve creating/adding a new developer to your developer account.

**Comment by ankushbadlas** [comment]
Hello ,
I am not able to get email address when I use ths ngx-facebook in my component. Please see my code.
facebookLogin(){
    const options: LoginOptions = {
        return_scopes: true,
        enable_profile_selector: true
      };

     this.fb.login(options)
     .then((response: LoginResponse) => {
       this.fbData = response.authResponse.accessToken;
      console.log(this.fbData);
      this.me(this.fbData);
     })
     .catch(e => console.error('Error logging in'));
  }

me(authResponse){
    let  self = this;
     this.fb.api('/me?fields=id,name,email,first_name,last_name,gender', 'get', {access_token:authResponse})
     .then(res => {
      console.log("user Results", res);
     })
     .catch(e => console.log(e));
  }

I got all other parameter like name, id first_name but I am not getting email address. Can anybody help me about this headache issue??

**Comment by kleeb** [comment]
I am having the same problem.
Facebook Graph Explorer throws some debug message 

`The field 'email' is only accessible on the User object after the user grants the 'email' permission.`

I have scope email and other addons added, but the user is asked only about his name and profile picture. It happens on every version. Refreshing token in explorer solves it, but no idea whats wrong inside the SDK.
