### ISSUE TITLE
404 GET <PATH>/node_modules/ng2-facebook-sdk/dist.js

### ISSUE THREAD

**Issue by SimoneCafiero** [zyramedia/ng2-facebook-sdk#25]
Hi,
on my side I got this message:

> 404 GET <PATH>/node_modules/ng2-facebook-sdk/dist.js

I included in index.html what follows:

> <script type="text/javascript" src="https://connect.facebook.net/en_US/sdk.js"></script>

Then in the systemjs.config.js:

```
map: {
  ...
 'ng2-facebook-sdk': 'npm:ng2-facebook-sdk'
},
packages: {
  ...
'ng2-facebook-sdk': {
                main: './ng2-facebook-sdk.js',
                defaultExtension: 'js'
            }

``````

Any idea?

**Comment by ihadeed** [comment]
Use this instead under `packages`:

```
      'ng2-facebook-sdk': {
        defaultExtension: 'js',
        main: './dist/index.js'
      }
```

**Comment by SimoneCafiero** [comment]
Hi ihadeed,
thanks but that didn't solve the issue.

Same problem.

**Comment by ihadeed** [comment]
How are you importing the provider from the npm package?

**Comment by SimoneCafiero** [comment]
Hi ihadeed,
thanks: that **solved** the issue.

Simone

**Comment by ihadeed** [comment]
Thanks for your feedback! Glad you got it working.

**Comment by gauravv7** [comment]
'ng2-facebook-sdk/dist': 'npm:ng2-facebook-sdk/dist/ng2-facebook-sdk.js', // mapping in system-config file
 packages: {
 ....
      'ng2-facebook-sdk/dist': {
        defaultExtension: 'js'
      }
    } // in system-config file

then all the imports works as given in the docs, works for me

**Comment by AsmaGargouri** [comment]
Thanks @ihadeed 
Using : 

```
map: {
  ...
 'ng2-facebook-sdk': 'npm:ng2-facebook-sdk'
},
```

and 

```
  'ng2-facebook-sdk': {
        defaultExtension: 'js',
        main: './dist/index.js'
      }
```

in jsystems.config.js solved my issue. Why is it not mentionned in the Read me althought?

**Comment by ihadeed** [comment]
@AsmaGargouri this is common SystemJS knowledge. It's not a quirk with this module.

**Comment by AsmaGargouri** [comment]
Oh ! My bad. Thank you.
