### ISSUE TITLE
API usage examples

### ISSUE THREAD

**Issue by ricardogomes** [zyramedia/ng2-facebook-sdk#26]
Hi

Do you have any API usage examples?

I'm trying to get the pages a user manages, to ultimately post to them.

This is a snippet of my code, but I'm not getting the same response as in the Graph Explorer

```
let options:FacebookLoginOptions = {
  scope:'publish_actions,manage_pages,publish_pages,pages_show_list'
}
this.facebookService.login().then(
  (response: FacebookLoginResponse) => {
    console.log(response);
    this.authResponse = response.authResponse;

    this.facebookService.api(this.authResponse.userID+'/accounts')
       .then((response)=>console.log(response));
 },
 (error: any) => console.error(error)
);
```

Thanks for this project, and your help.

**Comment by ihadeed** [comment]
Here's a block of code that I'm using in one of my applications:

```typescript
this.fb.login({
  scope: 'manage_pages,publish_pages'
}).then((userData: any) => {
    this.fb.api('/me/accounts', 'get', {
      perms: ['CREATE_CONTENT'] // get pages that the user can post to
    }).then(
      (res: any) => {
        let pagesList = res.data; // The pages that the user can post to
      },
      (err: any) => console.error(err)
    );
  },
  (err: any) => {
    console.error("Error logging in with Facebook: " + err);
  });
```

**Comment by ricardogomes** [comment]
Thanks @ihadeed it's was just a dumb bug. I forgot to pass the options to the login method.

**Comment by JackMj** [comment]
is it possible to get get page content of a different user, not one whos currently logged in but of a different account?

**Comment by ihadeed** [comment]
@JackMj you can use the `.api()` method to call the  `/{user-id}/feed` API endpoint. Replace `{user-id}` with the user id of the user. See https://developers.facebook.com/docs/graph-api/reference/v2.9/user/feed for more information.
