### ISSUE TITLE
Invalid version specified.

### ISSUE THREAD

**Issue by kleeb** [zyramedia/ng2-facebook-sdk#27]
Angular2 / Ionic2 app.
App is not being initialised and throws **invalid version specified**

Changing ```https://connect.facebook.net/en_US/sdk.js``` to ```https://connect.facebook.net/en_US/all.js``` solves the problem. Should it be like that?

**Comment by ihadeed** [comment]
That shouldn't be happening.

Are you specifying a version when you call the `init()` function?

In one of my applications, https://justpost.io, I'm specifying version `v2.6` and it's working fine.

**Comment by kleeb** [comment]
sure I am
couple days ago I was specifying version 2.8, as this is the latest one and everything worked
they must have changed something

anyone know the difference between sdk.js and all.js ?

**Comment by ihadeed** [comment]
@kleeb http://stackoverflow.com/questions/38462764/difference-between-facebook-all-js-and-sdk-js

**Comment by kleeb** [comment]
my fault, it works with version specified (no matter v2.8, v2.6 or other).
problems occurs when you don't specify anything (null or undefined)
