### ISSUE TITLE
Logout not working

### ISSUE THREAD

**Issue by oswaldosalazar** [zyramedia/ng2-facebook-sdk#28]
Hello all,
I'm currently using this in my project:
FBLogout() {
    this.fb.logout()
    .then(response => {
      console.log("Logout?", response);
    })
}
I assigned the function to a button and when I click it I get an error:
Refused to display 'https://www.facebook.com/home.php' in a frame because it set 'X-Frame-Options' to 'DENY'. And the user is still logged in. The console.log in never shown.
Any ideas?
Thanks!

**Comment by oswaldosalazar** [comment]
I sent you an email.

**Comment by ihadeed** [comment]
@oswaldosalazar Yes I got it. I will have a look at this later this evening or tomorrow morning.

**Comment by ihadeed** [comment]
@oswaldosalazar did you try this solution here: https://github.com/Ciul/angular-facebook/issues/92#issuecomment-77672899
