### ISSUE TITLE
login redirect uri blocked

### ISSUE THREAD

**Issue by gauravv7** [zyramedia/ng2-facebook-sdk#31]
Facebook login dialog says: "uri blocked",
I checked the return url for the test environment i created, but the url was not updating,
Checked in the changes for Fb.FacebookUiParams also but it is not updating, some staticxx.facebook.com url is always coming as the return URI in facebook login dialog.
Any solutions?

**Comment by gauravv7** [comment]
anyways i issued a test api for this, for the time being

**Comment by ihadeed** [comment]
Can you provide steps to reproduce this issue? 

I think you need to add your development URI as a valid redirect URI in your app settings (in Facebook Developers Console).
