### ISSUE TITLE
FacebookUiParams Interface

### ISSUE THREAD

**Issue by crsepulv** [zyramedia/ng2-facebook-sdk#32]
I'm trying to use FB.ui with the [Go Live Dialog](https://developers.facebook.com/docs/videos/live-video/exploring-live#golivedialog),  but transpiler says `Argument of type '{ display: string; method: string; phase: string; }' is not assignable to parameter of type 'FacebookUiParams'`

checking read.me there is no specification for FacebookUiParams Interface.

Do you have a time scope to add it?

**Comment by joejordanbrown** [comment]
#33

**Comment by ihadeed** [comment]
Merged the PR and will publish a new release now.
