### ISSUE TITLE
Missing parameter in FacebookAuthResponse

### ISSUE THREAD

**Issue by pawelkondraciuk** [zyramedia/ng2-facebook-sdk#35]
`grantedScopes` is missing in `FacebookAuthResponse`, it is returned when `return_scopes` is passed.
[Docs](https://developers.facebook.com/docs/reference/javascript/FB.login/v2.8)
<img width="681" alt="screen shot 2017-01-12 at 09 03 44" src="https://cloud.githubusercontent.com/assets/7136191/21881764/ea96651a-d8a7-11e6-9f63-93fb15a5b833.png">

**Comment by ihadeed** [comment]
Thanks I'll add this soon.

**Comment by ihadeed** [comment]
This is added and is available in the latest version `1.2.0`
