### ISSUE TITLE
Failed to load resource http://localhost:3000/ng2-facebook-sdk 

### ISSUE THREAD

**Issue by pickAUserName3** [zyramedia/ng2-facebook-sdk#39]
Browser gets stuck at loadiing.

Developer tools console shows the following
http://localhost:3000/ng2-facebook-sdk Failed to load resource: the server responded with a status of 404 (Not Found)

I have followed the steps in the readme. I am just running the basic example.

Thanks in advance for your help!

**Comment by ihadeed** [comment]
I'm guessing you're using  systemjs? Please see https://github.com/zyramedia/ng2-facebook-sdk/issues/25#issuecomment-263220566.

**Comment by pickAUserName3** [comment]
Thanks ihadeed, that was what I needed. I also want to use facebook login via pop up.Do you have an example I can refer to? 

I tried using the UI method but that just takes me to a complete Facebook login in a pop up. I would like to just see the username and password frame in pop up instead.

FBDialog() {
    this.fb.ui(
      {
        method: 'auth.login',
       })
      .then(
        (response) => {
          if (!response) {
            console.log('dialog canceled');
            return;
          }



![image](https://cloud.githubusercontent.com/assets/25317725/22282024/e0f18c56-e28e-11e6-8699-2e5052f447ca.png)

**Comment by ihadeed** [comment]
@pickAUserName3 see https://github.com/zyramedia/ng2-facebook-sdk#login
