### ISSUE TITLE
Facebook API Call using ng2-facebook-sdk

### ISSUE THREAD

**Issue by BearandYoon** [zyramedia/ng2-facebook-sdk#40]
I am using ng2-facebook-sdk to call some facebook endpoint on our project.
I have logged in using login endpoint of ng2-facebook-sdk.
I am trying to call acounts endpoint with manage_pages, publish_pages, pages_show_list options
FB.api(
    "/{user-id}/accounts",
    function (response) {
      if (response && !response.error) {
        /* handle the result */
      }
    }
);

how can I use the ng2-facebook-sdk endpoint to do this?

**Comment by ihadeed** [comment]
@BearandYoon you will need to use the `api` method.

```typescript
constructor(fb: FacebookService){ ... }

getAccounts() {

  this.fb.api('/{user-id}/accounts').then((resonse) => console.log(response));

}

```
