### ISSUE TITLE
Interface for params in api method

### ISSUE THREAD

**Issue by mjwdoek** [zyramedia/ng2-facebook-sdk#41]
Hi, can somebody provide me the interface for the params parameter in the api method?

api(path: string, method?: FacebookApiMethod, **params**?: any)

many thanks!

**Comment by ihadeed** [comment]
Hey @mjwdoek ,

The params for the `api` method depends on what method you're using. Each object/path in [Graph API Docs](https://developers.facebook.com/docs/graph-api/reference/) has a list of Parameters (if applicable). 

For example, if you have a look at the [`/user/accounts` reference page](https://developers.facebook.com/docs/graph-api/reference/user/accounts/), you will see a **Parameters** section. Most of the other objects do not accept any parameters. 

It's easier for us and for developers to leave the `params` type set to `any` in case of any future updates by Facebook.
