### ISSUE TITLE
Using FB Messenger Plugin

### ISSUE THREAD

**Issue by steady-daddy** [zyramedia/ng2-facebook-sdk#43]
How do I subscribe to Facebook messenger events using ng2-facebook-sdk?

The code without the library is as follows:

```
     FB.Event.subscribe('send_to_messenger', function(e) {
       // callback for events triggered by the plugin
    
     });
```

**Comment by ihadeed** [comment]
This functionality isn't implemented at the moment. I will add it as soon as I get a chance. Thank you for pointing it out.
