### ISSUE TITLE
Share dialog or popup in the center of the screen

### ISSUE THREAD

**Issue by HaraldBregu** [zyramedia/ng2-facebook-sdk#44]
Is possible to change the window position of the popup when trying to share? 
It is always in the bottom right.

**Comment by ihadeed** [comment]
There is no option for that. The Facebook SDK just opens a popup that will show based on the client's configuration/system. 

I personally never experienced the issue you mentioned. 

Did you try different computers?

**Comment by kodeine** [comment]
browsers are blocking the popup's. even on android 2nd attempt would work because first browser warns about the popup.
