### ISSUE TITLE
ng2-facebook-sdk 404 not found

### ISSUE THREAD

**Issue by Hanzofm** [zyramedia/ng2-facebook-sdk#45]
Hi

I'm trying to use your library to integrate facebook on my Angular 2 webApp.

I've installed the library and configured all steps but when start my webapp the inspector shows this error message and the webapp not start

GET http://localhost:3000/node_modules/ng2-facebook-sdk/ 404 (Not Found)       fetch:32

Could you help me?

**Comment by ihadeed** [comment]
I'm guessing you're using SystemJS. Please see related issues #25 #34.

**Comment by Hanzofm** [comment]
Thanks, issue #25 solved my problem
