### ISSUE TITLE
Share content directly without display the popup 

### ISSUE THREAD

**Issue by Hanzofm** [zyramedia/ng2-facebook-sdk#46]
Is possible to share content without show the dialog?

I've tried to set display option of `FacebookUiParams` to:
`"async", "hidden", or "none"`

But it doesn't works

Thanks

**Comment by ihadeed** [comment]
@Hanzofm 

I can't find documentation for that functionality here: https://developers.facebook.com/docs/sharing/reference/share-dialog

I personally don't think it's possible since that would allow webmasters to share content on users' profiles without them knowing.
