### ISSUE TITLE
404 - ng2-facebook-sdk/dist/ng2-facebook-sdk 

### ISSUE THREAD

**Issue by theromie** [zyramedia/ng2-facebook-sdk#49]
I am getting 404 error on ng2-facebook-sdk 
in my app.module.ts
import { FacebookService } from "ng2-facebook-sdk/dist/ng2-facebook-sdk";
providers: [FacebookService]

**Comment by ihadeed** [comment]
Duplicate of https://github.com/zyramedia/ng2-facebook-sdk/issues/25
