### ISSUE TITLE
ReferenceError: FB is not defined 

### ISSUE THREAD

**Issue by Dralac** [zyramedia/ng2-facebook-sdk#5]
@ihadeed I checked the closed issues, but nothing worked on my side. I've a script that includes FB SDK in header.
I'm trying to implement this with angular-universal starter project https://github.com/angular/universal-starter
Here is the component I'm trying to add FB login code provided in readme: https://github.com/angular/universal-starter/blob/master/src/app/home/home.component.ts

Any hints?

**Comment by ethanoic** [comment]
Having the same problems here today, @Dralac have you found a solution yet? its weird cos it worked the first time and subsequently the problem happens

**Comment by Dralac** [comment]
@ethanoic No, I didn't work on it yet, probably I'll try to solve it mid next week if we don't get any feedback.

**Comment by ihadeed** [comment]
Hey there,

Did you include the Facebook JavaScript SDK in your index.html?

This library is only a wrapper and does not actually contain the Facebook SDK. I apologize if the name is misleading. 

You must add `//connect.facebook.net/en_US/sdk.js` in a script tag before including the main app's JavaScript file.

**Comment by Dralac** [comment]
Hi @ihadeed 

Yes, SDK is available in index header on my side, as I stated above. Therefore I'm not sure why it's not working since everything is by the book. Seems it's initialized before SDK is ready. Not sure if you are using fbAsyncInit that ensures plugin is loaded when ready? 

Thank you

**Comment by ihadeed** [comment]
@Dralac 

No I'm not using `fbAsyncInit`.

I just used this wrapper in an Angular 2 (RC5) application and it worked fine. 

My code looks something like this:
```typescript
@Component({
  templateUrl: '/pages/connections/connections.html',
  providers: [FacebookService]
})
export class ConnectionsComponent {

  constructor(
    private fb: FacebookService
  ) {}

  ngOnInit(): void {
    this.fb.init({
      appId: '1234567890',
      xfbml: true,
      cookie: true,
      version: 'v2.6'
    });
  }
}
```

I don't see why the `fbAsyncInit` is needed since their JavaScript SDK is loaded synchronously as the page loads. As I understand, that method is used in case you would like to load the library asynchronously. ( See https://developers.facebook.com/docs/javascript/quickstart )

**Comment by Dralac** [comment]
@ihadeed 

You have a point, I just wanted to know if fbAsyncInit is supported so we can try that. I'll just consider this as an issue in universal or in my code. Anyway, thank you for your feedback. Cheers!

**Comment by ihadeed** [comment]
Can you provide the code you are using?

I haven't looked deeply into Angular Universal (waiting for things to get
stable). How does the implementation/script injection differ there?

**Comment by Dralac** [comment]
@ihadeed 
Sorry, I was on vacation. I think that issue is in angular universal, since I managed to use this project with pure angular code. 
Thanks or your time anyway, I'll close this one.
Cheers!

**Comment by flyplay91** [comment]
@ihadeed
I am on the same issue now.
I added script in index.html file.
But it is not working when I have karma unit test.
