### ISSUE TITLE
ZoneAwareError: (SystemJS) Unexpected value 'FacebookService'

### ISSUE THREAD

**Issue by JellyHuy** [zyramedia/ng2-facebook-sdk#50]
Hi

I previously had some problem that got resolved with issue #25 and #34, but now i stumple upon an issue saying:
ZoneAwareError {__zone_symbol__error: Error: (SystemJS) Unexpected value 'FacebookService' imported by the module 'AppModule'....}

Could you help me?

**Comment by ihadeed** [comment]
Can you share the code of your module page? That would be the page that contains `@NgModule(..)`

**Comment by JellyHuy** [comment]
This is my module page:
`import { FacebookService } from "ng2-facebook-sdk";`
pluss many other imports

`var appRoutes: Routes = [
    {path: '', component: AppComponentFrontPage},
    {path: 'AppComponentSideMenu', component: AppComponentSideMenu, children: [
      {path: '', component: AppComponentOverview},
      {path: 'AppComponentCustomAudience', component: AppComponentCustomAudience }
    ]},
    {path: 'AppComponentDoc', component: AppComponentDoc}
]`

`@NgModule({ imports: [
        BrowserModule, HttpModule, JsonpModule,
        FormsModule, ReactiveFormsModule,
        RouterModule.forRoot(appRoutes)
    ],
    declarations: [
      AppComponent,
      AppComponentFrontPage,
      AppComponentSideMenu,
      AppComponentCustomAudience,
      AppComponentOverview,
      AppComponentDoc
    ],
    providers: [{ provide: LocationStrategy, useClass: HashLocationStrategy }, FacebookService],
    bootstrap:    [AppComponent]
})
export class AppModule { }
`

i also tried to add FacebookService in the imports of `@NgModule` with no result.

**Comment by ihadeed** [comment]
Everything looks good to me. Try reinstalling your `node_modules` and clearing browser cache.

Do you have issues running the example project here: https://github.com/zyramedia/ng2-facebook-sdk-example ?

**Comment by JellyHuy** [comment]
I just tried to run example project and it works perfecly fine without any issues or errors, except for when i write http:// before localhost in my browser i get:
localhost unexpectedly closed the connection.

unexpected the problem solved on its own and its working now. I think the problem lies in the browser cache as the browser cleared it after a while and it works now, as you mention about it 

Thank you for your help and time!
