### ISSUE TITLE
getLoginStatus() and Chrome

### ISSUE THREAD

**Issue by ThomasKientz** [zyramedia/ng2-facebook-sdk#51]
I had to clean my chrome caches and cookies to make it works for a few time, maybe like 5-10 calls, then i get a 'unknown' status in the response. But it works like a charm on safari, tested on different computers. 

Do you have this same issue ?

**Comment by ihadeed** [comment]
I personally don't use `getLoginStatus()`. I just call the `login` method whenever I start a new session.

Anyways, this would be an issue with the Facebook SDK and not with this wrapper. Feel free to discuss it here but I'm going to close the issue.
