### ISSUE TITLE
webpack warning: Cannot find source file

### ISSUE THREAD

**Issue by berhir** [zyramedia/ng2-facebook-sdk#54]
I use webpack to bundle my project and it always shows this warning:
```
WARNING in ./~/ng2-facebook-sdk/dist/index.js
Cannot find source file '../src/index.ts': Error: Can't resolve '../src/index.ts' in C:\...\node_modules\ng2-facebook-sdk\dist'
 @ ./src/app/components/app.component.ts 12:0-51
 @ ./src/app/app.module.ts
 @ ./src/main.ts
 @ multi ./src/main.ts
```

The problem is that you provide a map file but the referenced code file is missing.  
Can you remove the map file or add the source files to the package? Because it doesn't really make sense to have the map files without the source files. Or am I wrong?  
Thanks!

**Comment by ihadeed** [comment]
Yeah you're right, source files should be there if the source map is provided. 

I just fixed it and published `ng2-facebook-sdk@1.2.1`.
