### ISSUE TITLE
ng2-facebook-sdk not installing!

### ISSUE THREAD

**Issue by romafederico** [zyramedia/ng2-facebook-sdk#56]
Hi there.

I just did 

> npm i --save ng2-facebook-sdk

And I got the following error

> > npm ERR! Darwin 16.1.0
> npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "i" "--save" "ng2-facebook-sdk"
> npm ERR! node v6.10.0
> npm ERR! npm  v3.10.10
> npm ERR! path /Users/Fede/dev/bukium-rel/node_modules/bootstrap
> npm ERR! code EISGIT
> 
> npm ERR! git /Users/Fede/dev/bukium-rel/node_modules/bootstrap: Appears to be a git repo or submodule.
> npm ERR! git     /Users/Fede/dev/bukium-rel/node_modules/bootstrap
> npm ERR! git Refusing to remove it. Update manually,
> npm ERR! git or move it out of the way first.
> 
> npm ERR! Please include the following file with any support request:
> npm ERR!     /Users/Fede/dev/bukium-rel/npm-debug.log

What am I doing wrong?

**Comment by ihadeed** [comment]
Doesn't seem to be an issue with this module.

I think your `bootstrap` module has a `.git` directory that is causing this issue. Run this command to remove any `.git` directories from `node_modules`:

```
rm -rf node_modules/*/.git/
```
