### ISSUE TITLE
FacebookUiParams should support message

### ISSUE THREAD

**Issue by shramee** [zyramedia/ng2-facebook-sdk#57]
Hi guys,
first of all thanks for such a lovely plugin... 😄 

I got this issue while tryna implement game requests...

Argument of type `{ method: string; message: string; }` is not assignable to parameter of type 'FacebookUiParams'.

`message` is used in `apprequests` ui method.
https://developers.facebook.com/docs/games/services/gamerequests#jssdk

**Comment by ihadeed** [comment]
Just published `ng2-facebook-sdk@1.4.0` with this fix included.
