### ISSUE TITLE
Not working with SystemJS module loader

### ISSUE THREAD

**Issue by dinkomanolov** [zyramedia/ng2-facebook-sdk#64]
This module cannot be used with SystemJS module loader. 
Can you build umd file? 
Thank you.

**Comment by ihadeed** [comment]
Hey there,

Please update to `ng2-facebook-sdk@2.2.0`. Let me know if all works well, I haven't tested it fully. I just made sure it doesn't break existing code.

**Comment by dinkomanolov** [comment]
It works perfect. 
Thank you very much.

**Comment by ihadeed** [comment]
Great! Thanks for the update.
