### ISSUE TITLE
Edit documentation

### ISSUE THREAD

**Issue by alouane** [zyramedia/ng2-facebook-sdk#68]
Hi there,
Check please this link: https://zyramedia.github.io/ng2-facebook-sdk/facebook-service/
there is a typo error in this line scope: **public_profiel**, user_friends,email,pages_show_list

it should be fixed cauze we all do copy & paste blindly & it causes a 500 fb api error :)

Thanks

**Comment by ihadeed** [comment]
Thanks, just fixed it!
