### ISSUE TITLE
Can we change from Promise to Observable?

### ISSUE THREAD

**Issue by sunshineo** [zyramedia/ng2-facebook-sdk#8]
It seems to me that Angular2 is all Observable yet this project is using Promise.
Result in the code I wrote looks very strange. And I'm having a hard time to chain things properly.

**Comment by ihadeed** [comment]
Observables are usually used for events (their callback can be triggered
multiple times). Promises are used when the callback gets triggered once,
which seems to be the case with the Facebook JavaScript SDK.

**Comment by sunshineo** [comment]
But @angular/http does not return Promise but Observable.

**Comment by ihadeed** [comment]
I had a look at the API again and I don't think any of the methods need to return an Observable. Going to close this for now. But if you can share a use case where an observable would make more sense, we can investigate this further.

**Comment by patrickmichalina** [comment]
It would be better as an observable since you can flatMap and join other streams fluently....
